databases:
  - name: todo_db
    databaseName: todo_db
    user: todo_user
    plan: free

services:
  - type: web
    name: todo-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todo_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: todo_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: FRONTEND_URL
        value: https://todo-app-frontend-somu.vercel.app
